### PR TITLE
feat: sourcemap

### PR DESCRIPTION
**Pull request by yankeeinlondon**
There were a lot of code changes in v0.12.0 and the original PR has been getting a bit stale and needed consistent linting. This PR adjusts for these two factors but I am no expert on source-maps and really not sure if the source maps are valid. 

@HomyeeKing would you willing to add in a unit test and make sure this is all working?
@HomyeeKing I switched use from `source-map` module to `source-map-js` modules which I think is probably the better upstream dependency (and has the same API surface); not my area of expertise though so maybe i'm wrong
@antfu how are you meant to add the _map_ data back into the ViteJS build pipeline? From what I was seeing there was code to generate the source mapping but it didn't appear to be reintroduced to the overall pipeline. As it stands now, i've added a `map` property to this plugin's pipeline payload but it doesn't go anywhere.

### CODE REVIEW

**Comment by HomyeeKing** [comment]
@yankeeinlondon  Thank you for picking up this stale pr and put into effort👍. 

Here's my viewpoint about the sourcemap:
```mermaid
 flowchart LR
    md[markdown]
    vueMd[vue syntax]
    compiledVue[compiled Vue]

 md  -- vite-plugin-md --> vueMd  -- vite-plugin-vue --> compiledVue
compiledVue --sourcemap2 --> vueMd --sourcemap1 --> md
```

I think we should focus on  the `sourcemap1` since the _source_ is the markdown file written by developer and  the `sourcemap1` would be  helpful locate the error

as for  `sourcemap2`,  which's currently implemented should be cared by vite-plugin-vue I think

**Review by antfu — APPROVED** [review]

**Comment by yankeeinlondon** [comment]
@HomyeeKing @antfu just a quick clarification ... I wanted to get this PR really ready for release and I'm a bit uncertain on an aspect I'd like feedback on. 

The ViteJS pipeline of transforms involved today to convert a Markdown file to Javascript is:
- this plugin receives imported `.md` files and tranforms them to an SFC file format (which can include custom blocks but always contains Script and Template blocks
- the `@vitejs/plugin-vue` receives this transformed file and converts it to JS and CSS

When we talk about "sourcemaps", I think @HomyeeKing's mermaid diagram is critical instruction as it points to this plugin's responsibility being the conversion of MD to SFC and leaves the second transform's responsibility (aka, SFC to JS/CSS) to `@vitejs/plugin-vue`. Seems like good separation of concerns at least on the surface (though the intermediate form might be useful in understanding some issues as well). 

Are we in agreement on this?

**Comment by antfu** [comment]
Yeah, I think we only generate the source map to Vue SFC makes sense.

**Comment by yankeeinlondon** [comment]
i'm closing this as a working copy is now in `main` and I'm trying to release as `v0.17.0` but appear to have a failed action which I need to look into.

**Pull request closed without merging**
